/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FormulariosBH;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdazt
 */
public class BuscarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarUsuario
     */
    DefaultTableModel modelo;

    public BuscarUsuario() {
        initComponents();
        PrepararTabla();
        cargarDatosAlModel();
    }

    private void PrepararTabla() {
        String titulos[] = {"Cédula", "Nombre", "E-mail", "Dirección", "# Silla", "Clase"};
        modelo = new DefaultTableModel(null, titulos);
        tbClientes.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Usuario");

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbClientes);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("BUSCAR USUARIO");

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public File[] getTxtFiles(String directory) {
        File dir = new File(directory);
        if (dir.isDirectory()) {
            return dir.listFiles((dir1, name) -> name.endsWith(".txt"));
        }
        return null;
    }

    private void cargarDatosAlModel() {
        PrepararTabla();
        String pathClientes = "C:\\Users\\Usuario\\OneDrive\\Escritorio\\Clientes";
        String pathVuelos = "C:\\Users\\Usuario\\OneDrive\\Escritorio\\Vuelos";
        File[] listaArchivosClientes = getTxtFiles(pathClientes);
        File[] listaArchivosVuelos = getTxtFiles(pathVuelos);

        for (File fileCliente : listaArchivosClientes) {
            String cedulaCliente = "";
            String nombreCliente = "";
            String emailCliente = "";
            String direccionCliente = "";

            // Leer datos del cliente
            try (BufferedReader brCliente = new BufferedReader(new FileReader(fileCliente))) {
                String line;
                while ((line = brCliente.readLine()) != null) {
                    line = line.replaceAll("\n", "");
                    String[] partes = line.split("=");
                    if (partes.length == 2) {
                        switch (partes[0]) {
                            case "Cédula":
                                cedulaCliente = partes[1];
                                break;
                            case "Nombre":
                                nombreCliente = partes[1];
                                break;
                            case "E-mail":
                                emailCliente = partes[1];
                                break;
                            case "Dirección":
                                direccionCliente = partes[1];
                                break;
                        }
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al cargar datos del cliente: " + e.getMessage());
            }

            for (File fileVuelo : listaArchivosVuelos) {
                String nSilla = "";
                String claseSilla = "";
                String usuario = "";

                // Leer datos del vuelo
                try (BufferedReader brVuelo = new BufferedReader(new FileReader(fileVuelo))) {
                    String line;
                    while ((line = brVuelo.readLine()) != null) {
                        line = line.replaceAll("\n", "");
                        String[] partes = line.split("=");
                        if (partes.length == 2) {
                            switch (partes[0]) {
                                case "NSilla":
                                    nSilla = partes[1];
                                    break;
                                case "ClaseSilla":
                                    claseSilla = partes[1];
                                    break;
                                case "Usuario":
                                    usuario = partes[1];
                                    break;
                            }
                        }
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al cargar datos del vuelo: " + e.getMessage());
                }

                // Comprobar si las cédulas coinciden
                if (cedulaCliente.equals(usuario)) {
                    String[] nuevaFila = {cedulaCliente, nombreCliente, emailCliente, direccionCliente, nSilla, claseSilla};
                    modelo.addRow(nuevaFila);
                }
            }
        }
    }

    private void buscarClienteText(String identificacion) {
        PrepararTabla();
        String path = "C:\\Users\\Usuario\\OneDrive\\Escritorio\\Clientes";
        String pathVuelos = "C:\\Users\\Usuario\\OneDrive\\Escritorio\\Vuelos";
        File[] listaArchivosVuelos = getTxtFiles(pathVuelos);
        File[] listaArchivos = getTxtFiles(path);
        String Email = "", Contraseña = "", Cedula = "", Nombre = "", Edad = "", Direccion = "";
        for (File file : listaArchivos) {
            System.out.println("Contenido del archivo " + file.getName());
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;

                while ((line = br.readLine()) != null) {
                    line = line.replaceAll("\n", "");
                    String[] partes = line.split("=");
                    if (partes.length == 2) {
                        switch (partes[0]) {
                            case "E-mail":
                                Email = partes[1];
                                break;
                            case "Contraseña":
                                Contraseña = partes[1];
                                break;
                            case "Cédula":
                                Cedula = partes[1];
                                break;
                            case "Nombre":
                                Nombre = partes[1];
                                break;
                            case "Edad":
                                Edad = partes[1];
                                break;
                            case "Dirección":
                                Direccion = partes[1];
                                break;
                        }
                    }
                }

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error en el cargar datos: " + e.getMessage());
            }

            for (File fileVuelo : listaArchivosVuelos) {
                String nSilla = "";
                String claseSilla = "";
                String usuario = "";

                // Leer datos del vuelo
                try (BufferedReader brVuelo = new BufferedReader(new FileReader(fileVuelo))) {
                    String line;
                    while ((line = brVuelo.readLine()) != null) {
                        line = line.replaceAll("\n", "");
                        String[] partes = line.split("=");
                        if (partes.length == 2) {
                            switch (partes[0]) {
                                case "NSilla":
                                    nSilla = partes[1];
                                    break;
                                case "ClaseSilla":
                                    claseSilla = partes[1];
                                    break;
                                case "Usuario":
                                    usuario = partes[1];
                                    break;
                            }
                        }
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al cargar datos del vuelo: " + e.getMessage());
                }

// Comprobar si las cédulas coinciden
                if (Cedula.equals(identificacion)) {
                    if (Cedula.equals(usuario)) {
                        String[] nuevaFila = {Cedula, Nombre, Email, Direccion, nSilla, claseSilla};
                        modelo.addRow(nuevaFila);
                    }
                }
            }
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String identificacion = txtBuscar.getText().trim();
        if (identificacion.trim().equals("")) {
            cargarDatosAlModel();
        } else {
            buscarClienteText(identificacion);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbClientes.getModel();
        int rowCount = modelo.getRowCount();
        String[] nombres = new String[rowCount];

        for (int i = 0; i < rowCount; i++) {
            nombres[i] = (String) modelo.getValueAt(i, 1);
        }

        shellSort(nombres);

        for (int i = 0; i < rowCount; i++) {
            modelo.setValueAt(nombres[i], i, 1);
        }
    }

    private void shellSort(String[] arr) {
        int n = arr.length;
        for (int gap = n / 2; gap > 0; gap /= 2) {
            for (int i = gap; i < n; i++) {
                String temp = arr[i];
                int j;
                for (j = i; j >= gap && arr[j - gap].compareTo(temp) > 0; j -= gap) {
                    arr[j] = arr[j - gap];
                }
                arr[j] = temp;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
